export const stackOfCards = [
  { name: "Ace of Spades", value: 11, image: "images/cards/spades_A.png" },
  { name: "2 of Spades", value: 2, image: "images/cards/spades_2.png" },
  { name: "3 of Spades", value: 3, image: "images/cards/spades_3.png" },
  { name: "4 of Spades", value: 4, image: "images/cards/spades_4.png" },
  { name: "5 of Spades", value: 5, image: "images/cards/spades_5.png" },
  { name: "6 of Spades", value: 6, image: "images/cards/spades_6.png" },
  { name: "7 of Spades", value: 7, image: "images/cards/spades_7.png" },
  { name: "8 of Spades", value: 8, image: "images/cards/spades_8.png" },
  { name: "9 of Spades", value: 9, image: "images/cards/spades_9.png" },
  { name: "10 of Spades", value: 10, image: "images/cards/spades_10.png" },
  {
    name: "Jack of Spades",
    value: 10,
    image: "images/cards/spades_J.png",
  },
  {
    name: "Queen of Spades",
    value: 10,
    image: "images/cards/spades_Q.png",
  },
  {
    name: "King of Spades",
    value: 10,
    image: "images/cards/spades_K.png",
  },

  { name: "Ace of Hearts", value: 11, image: "images/cards/hearts_A.png" },
  { name: "2 of Hearts", value: 2, image: "images/cards/hearts_2.png" },
  { name: "3 of Hearts", value: 3, image: "images/cards/hearts_3.png" },
  { name: "4 of Hearts", value: 4, image: "images/cards/hearts_4.png" },
  { name: "5 of Hearts", value: 5, image: "images/cards/hearts_5.png" },
  { name: "6 of Hearts", value: 6, image: "images/cards/hearts_6.png" },
  { name: "7 of Hearts", value: 7, image: "images/cards/hearts_7.png" },
  { name: "8 of Hearts", value: 8, image: "images/cards/hearts_8.png" },
  { name: "9 of Hearts", value: 9, image: "images/cards/hearts_9.png" },
  { name: "10 of Hearts", value: 10, image: "images/cards/hearts_10.png" },
  {
    name: "Jack of Hearts",
    value: 10,
    image: "images/cards/hearts_J.png",
  },
  {
    name: "Queen of Hearts",
    value: 10,
    image: "images/cards/hearts_Q.png",
  },
  {
    name: "King of Hearts",
    value: 10,
    image: "images/cards/hearts_K.png",
  },

  { name: "Ace of Clubs", value: 11, image: "images/cards/clubs_A.png" },
  { name: "2 of Clubs", value: 2, image: "images/cards/clubs_2.png" },
  { name: "3 of Clubs", value: 3, image: "images/cards/clubs_3.png" },
  { name: "4 of Clubs", value: 4, image: "images/cards/clubs_4.png" },
  { name: "5 of Clubs", value: 5, image: "images/cards/clubs_5.png" },
  { name: "6 of Clubs", value: 6, image: "images/cards/clubs_6.png" },
  { name: "7 of Clubs", value: 7, image: "images/cards/clubs_7.png" },
  { name: "8 of Clubs", value: 8, image: "images/cards/clubs_8.png" },
  { name: "9 of Clubs", value: 9, image: "images/cards/clubs_9.png" },
  { name: "10 of Clubs", value: 10, image: "images/cards/clubs_10.png" },
  { name: "Jack of Clubs", value: 10, image: "images/cards/clubs_J.png" },
  {
    name: "Queen of Clubs",
    value: 10,
    image: "images/cards/clubs_Q.png",
  },
  { name: "King of Clubs", value: 10, image: "images/cards/clubs_K.png" },

  {
    name: "Ace of Diamonds",
    value: 11,
    image: "images/cards/diamonds_A.png",
  },
  { name: "2 of Diamonds", value: 2, image: "images/cards/diamonds_2.png" },
  { name: "3 of Diamonds", value: 3, image: "images/cards/diamonds_3.png" },
  { name: "4 of Diamonds", value: 4, image: "images/cards/diamonds_4.png" },
  { name: "5 of Diamonds", value: 5, image: "images/cards/diamonds_5.png" },
  { name: "6 of Diamonds", value: 6, image: "images/cards/diamonds_6.png" },
  { name: "7 of Diamonds", value: 7, image: "images/cards/diamonds_7.png" },
  { name: "8 of Diamonds", value: 8, image: "images/cards/diamonds_8.png" },
  { name: "9 of Diamonds", value: 9, image: "images/cards/diamonds_9.png" },
  {
    name: "10 of Diamonds",
    value: 10,
    image: "images/cards/diamonds_10.png",
  },
  {
    name: "Jack of Diamonds",
    value: 10,
    image: "images/cards/diamonds_J.png",
  },
  {
    name: "Queen of Diamonds",
    value: 10,
    image: "images/cards/diamonds_Q.png",
  },
  {
    name: "King of Diamonds",
    value: 10,
    image: "images/cards/diamonds_K.png",
  },
];
